ARCH="x86"
OUTPUT_TYPE="iso"
GRUB_PREFIX="/usr/local/"
ASM="build/fasm.exe"
CC="i386-elf-gcc"
LD="i386-elf-ld"
ASMARGS=""
CCARGS="-O3 -m32 -nostdlib -nostartfiles -nodefaultlibs"
LDARGS=""
BUILDLOG="buildlog.txt"
GRUB_MKRESCUE=`which grub-mkrescue`
QEMU=`which qemu`
